apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: internet-bank
  labels:
    app: api
data:
  application.properties: |
    server.port=8282
  REDIS_HOST: redis
  OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4317
