apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: internet-bank/api-application:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8282
          readinessProbe:
            httpGet:
              path: /api/fac/1
              port: 8282
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/fac/1
              port: 8282
            initialDelaySeconds: 30
            periodSeconds: 15
