apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: internet-bank
type: Opaque
stringData:
  POSTGRES_USER: "bankuser"
  POSTGRES_PASSWORD: "pUQX0eja56l0bLBR8u9Wb3KOI43E1o5"
  DATABASE_URL: "jdbc:postgresql://postgres:5432/internet_bank?user=bankuser&password=pUQX0eja56l0bLBR8u9Wb3KOI43E1o5"
