apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: internet-bank
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'spring-boot-api'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['api.internet-bank.svc.cluster.local:8282']
            labels:
              service: 'internet-bank-api'

      - job_name: 'postgres'
        static_configs:
          - targets: ['postgres-exporter.internet-bank.svc.cluster.local:9187']
            labels:
              service: 'internet-bank-postgres'

      - job_name: 'tempo'
        static_configs:
          - targets: ['tempo.internet-bank.svc.cluster.local:3200']
            labels:
              service: 'internet-bank-tempo'
