apiVersion: v1
kind: Service
metadata:
  name: web-client
  namespace: internet-bank
  labels:
    app: web-client
spec:
  type: ClusterIP
  selector:
    app: web-client
  ports:
    - port: 80
      targetPort: 8080
