apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-client-ingress
  namespace: internet-bank
  labels:
    app: web-client
spec:
  rules:
    - host: web-client.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-client
                port:
                  number: 80
